import {Group, GroupUser, Status, User} from './model';

export const GROUPS: Group[] = [
  {group_id: 1, name: 'base group', description: undefined, status: 2, parent_id: 1},
  {group_id: 2, name: 'group 2', description: undefined, status: 0, parent_id: 1},
  {group_id: 3, name: 'group 3', description: undefined, status: 1, parent_id: 1},
  {group_id: 4, name: 'group 4', description: undefined, status: 2, parent_id: 1},
  {group_id: 5, name: 'group 5', description: undefined, status: 2, parent_id: 1}
];

export const USERS: User[] = [
  {
    user_id: 1,
    user_name: 'hieuvt',
    password: '1234',
    expire_status: 2,
    full_name: 'vuong trung hieu',
    status: 2,
    phone: '0973804435',
    mobile: '0973804435',
    fax: 'hieuvt@telsoft.com',
    email: 'hieuvt@telsoft.com.vn',
    address: 'hanoi',
    modified_password: undefined,
    locked_date: undefined,
    failure_count: 0,
    created_id: 1,
    deleted_id: undefined,
    modified_id: undefined,
    config: ''
  },
  {
    user_id: 2,
    user_name: 'chiendx',
    password: '1234',
    expire_status: 2,
    full_name: 'chiendx',
    status: 2,
    phone: '0973804435',
    mobile: '0973804435',
    fax: 'chiendx@telsoft.com',
    email: 'chiendx@telsoft.com.vn',
    address: 'hanoi',
    modified_password: undefined,
    locked_date: undefined,
    failure_count: 0,
    created_id: 2,
    deleted_id: undefined,
    modified_id: undefined,
    config: ''
  },
  {
    user_id: 3,
    user_name: 'tiennv',
    password: '1234',
    expire_status: 2,
    full_name: 'tiennv',
    status: 2,
    phone: '0973804435',
    mobile: '0973804435',
    fax: 'tiennv@telsoft.com',
    email: 'tiennv@telsoft.com.vn',
    address: 'hanoi',
    modified_password: undefined,
    locked_date: undefined,
    failure_count: 0,
    created_id: 3,
    deleted_id: undefined,
    modified_id: undefined,
    config: ''
  },
  {
    user_id: 4,
    user_name: 'linhnc',
    password: '1234',
    expire_status: 2,
    full_name: 'linhnc',
    status: 2,
    phone: '0973804435',
    mobile: '0973804435',
    fax: 'linhnc@telsoft.com',
    email: 'linhnc@telsoft.com.vn',
    address: 'hanoi',
    modified_password: undefined,
    locked_date: undefined,
    failure_count: 0,
    created_id: 4,
    deleted_id: undefined,
    modified_id: undefined,
    config: ''
  },
  {
    user_id: 5,
    user_name: 'khanhdd',
    password: '1234',
    expire_status: 2,
    full_name: 'khanhdd',
    status: 2,
    phone: '0973804435',
    mobile: '0973804435',
    fax: 'khanhdd@telsoft.com',
    email: 'khanhdd@telsoft.com.vn',
    address: 'hanoi',
    modified_password: undefined,
    locked_date: undefined,
    failure_count: 0,
    created_id: 5,
    deleted_id: undefined,
    modified_id: undefined,
    config: ''
  },
  {
    user_id: 6,
    user_name: 'khanhnc',
    password: '1234',
    expire_status: 2,
    full_name: 'khanhnc',
    status: 2,
    phone: '0973804435',
    mobile: '0973804435',
    fax: 'khanhnc@telsoft.com',
    email: 'khanhnc@telsoft.com.vn',
    address: 'hanoi',
    modified_password: undefined,
    locked_date: undefined,
    failure_count: 0,
    created_id: 6,
    deleted_id: undefined,
    modified_id: undefined,
    config: ''
  },
  {
    user_id: 7,
    user_name: 'linhdtt',
    password: '1234',
    expire_status: 2,
    full_name: 'linhdtt',
    status: 2,
    phone: '0973804435',
    mobile: '0973804435',
    fax: 'linhdtt@telsoft.com',
    email: 'linhdtt@telsoft.com.vn',
    address: 'hanoi',
    modified_password: undefined,
    locked_date: undefined,
    failure_count: 0,
    created_id: 7,
    deleted_id: undefined,
    modified_id: undefined,
    config: ''
  }
];

export const GROUP_USERS: GroupUser[] = [
  {id: 1, group_id: 1, user_id: 1},
  {id: 2, group_id: 4, user_id: 2},
  {id: 3, group_id: 3, user_id: 3},
  {id: 4, group_id: 1, user_id: 4},
  {id: 5, group_id: 1, user_id: 5}
];
